[package]
name = "cargo-incremental"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
docopt = "0.6.82"
git2 = "0.4.4"
regex = "0.1.73"
rustc-serialize = "0.3.19"
progress = "0.2"